FROM ubuntu:14.04.4

ADD ./emdebian-toolchain-archive.key .

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsL http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gmp4/libgmp3c2_4.3.2+dfsg-2ubuntu1_amd64.deb -o libgmp3c2_4.3.2+dfsg-1_amd64.deb && \
    dpkg -i /libgmp3c2_4.3.2+dfsg-1_amd64.deb && \
    echo "deb http://www.emdebian.org/debian stable main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-key add emdebian-toolchain-archive.key && \
    apt-get install debian-archive-keyring && \
    apt-get install -y --force-yes \
        build-essential \
	    cpp-4.3-mips-linux-gnu \
		gcc-4.3-mips-linux-gnu \
		gdb-multiarch \
		git \
		libexif12 \
		python \
		qemu-system-mips \
		qemu-user

RUN mkdir -p /import/ && mkdir -p /out/
COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
